Wh11
Yura-Panchenko/js-learn pull request #7
Opened 2022-10-14 20:06 UTC by Yura-Panchenko

2022-10-15 17:43 UTC, vb-oiko commented on wh10/js/main.js
> +    el = prompt('Enter nuber','');
Було б добре повидомити користувачу, як завершити ввод елементів
```suggestion
    el = prompt('Enter array element, press "Esc" when finished','');
```

2022-10-15 17:45 UTC, vb-oiko commented on wh11/js/main.js
> +let arr1 = arr.filter((el) => {
було б краще назвати цю зміну наприклад `positiveArray`

2022-10-15 17:46 UTC, vb-oiko commented on wh11/js/main.js
> +    return result += el;
не треба змінювати аргументи фунції - це погана практика, хоча і цілком валідний код
```suggestion
    return result + el;
```

2022-10-15 17:47 UTC, vb-oiko commented on wh11/js/main.js
> +    return acc = Math.min(acc,el);
```suggestion
    return Math.min(acc,el);
```

2022-10-15 17:52 UTC, vb-oiko requested changes
На лекції ми розглянули, що параметри функції є фактично локальними змінними. Але я не сказав що змінювати параметри функції це погана пркатика - ніколи такого не бачив.
Я приношу вибачення, що не попередив. Прошу виправити усі подібні випадки.

2022-10-16 00:16 UTC, melnikovweb approved these changes

2022-10-16 00:18 UTC, melnikovweb commented
Будь ласка виправте помилки які вказав викладач

2022-10-17 20:07 UTC, merged